language: node_js
node_js:
    - "4"
    - "6"

before_script:

script:
    - npm test
    - node index.js

after_success:
#   - npm install istanbul codecov
#   - npm run cover
#   - ./node_modules/.bin/codecov

sudo: false
