name: CI

on: [ push, pull_request ]

env:
  CI: true

jobs:

  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  test:
    needs: [ lint ]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master

  windows:
    uses: haraka/.github/.github/workflows/windows.yml@master
